# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  http-reverse-proxies:
    description: |
      Comma separated list of reverse proxies to setup in the format
      :<HOST-PORT>:<REMOTE-IP>:<REMOTE-PORT>
    type: string
  https-reverse-proxies:
    description: |
      Comma separated list of reverse proxies to setup in the format
      :<HOST-PORT>:<REMOTE-IP>:<REMOTE-PORT>
    type: string
